baseURL = 'http://andrewsblog.rocks/'
languageCode = 'en-us'
title = "Andrew's Blog"
theme = "paper"

# disqusShortname = 'YOUR_DISQUS_SHORTNAME'   # add disqus comments

[params]
  # disableHLJS = true                         # don't use highlight.js
  twitter = 'andrewmreal'                # twitter.com/YOUR_TWITTER_ID
  github = 'realandrew'                  # github.com/YOUR_GITHUB_ID
  # instagram = 'YOUR_INSTAGRAM_ID'            # instagram.com/YOUR_INSTAGRAM_ID
